import { test, expect } from '@playwright/test';
import { RetailLoanPayoffPage } from '../../pages/CoreBanking/RetailLoanPayoffPage';
import { ServicePackPage } from '../../pages/servicepackpage';
import { loginToFinacle } from '../../helpers/finacleSetup';
import { CREDENTIALS } from '../../../data/credentials';
import { getSharedValue } from '../../helpers/sharedState';

// Verifier user who authorises the retail-loan payoff.
const USERNAME = CREDENTIALS.verifierCredentials.username;
const PASSWORD = CREDENTIALS.verifierCredentials.password;

// Loan account number generated by Retailloancreation.spec.ts.
const SHARED_LOAN_ACCOUNT = getSharedValue<string>('loanAccountId');
const LOAN_ACCOUNT_NUMBER = SHARED_LOAN_ACCOUNT ?? '3200000056';
if (SHARED_LOAN_ACCOUNT) console.log(`[SharedState] Using Loan Account ID from previous run: ${SHARED_LOAN_ACCOUNT}`);

test('HPAYOFF - payoff verification for retail loan', async ({ page }) => {
  test.setTimeout(300000);
  page.setDefaultTimeout(20000);

  const { homePage } = await loginToFinacle(page, USERNAME, PASSWORD);
  const payoffPage = new RetailLoanPayoffPage(page);

  try {
    const result = await payoffPage.verifyPayoff({
      loanAccountNumber: LOAN_ACCOUNT_NUMBER,
    });

    console.log('====================================');
    console.log('Payoff verification transaction ID:', result.transactionId);
    console.log('Payoff verification message:', result.message);
    console.log('====================================');

    const servicePackPage = new ServicePackPage(page);
    await servicePackPage.servicePackRetailLoanPayoffVerificationValidation({
      loanAccountNumber: LOAN_ACCOUNT_NUMBER,
      transactionId: result.transactionId,
      message: result.message,
      screenshot: result.screenshot,
    });
  } finally {
    await homePage.logout().catch(() => {});
  }
});

// === STRICT ASSERTIONS INJECTION ===
test.afterEach(async ({ page }) => {
  const html = (await page.content()).toLowerCase();
  expect(html).not.toMatch(/core dump|internal server error/);
});
