import { test } from '@playwright/test';
import { HomePage } from '../../../pages/HomePage';
import { SavingsBankAccountPage } from '../../../pages/SavingsBankAccountPage';
import { loginToFinacle } from '../../helpers/finacleSetup';
import COMMON_DATA from '../../../data/common-data.json';

// Verification must be performed by a DIFFERENT user than the maker who opened
// the loan (the account was created by finacletest01 in Retailloancreation.spec).
const USERNAME = COMMON_DATA.verifierCredentials.username;
const PASSWORD = COMMON_DATA.verifierCredentials.password;

// Loan account number generated by Retailloancreation.spec.ts. Update this with
// the latest generated loan A/c ID before running the verification.
const LOAN_ACCOUNT_NUMBER = '3200000043';

let homePage: HomePage;
let loanPage: SavingsBankAccountPage;

test.beforeEach(async ({ page }) => {
  test.setTimeout(300000);
  page.setDefaultTimeout(20000);

  // Step 1: Login with a different user (verifier) than the maker.
  ({ homePage } = await loginToFinacle(page, USERNAME, PASSWORD));
  loanPage = new SavingsBankAccountPage(page);
});

// HOAACVLA - Verify/authorise a retail loan account opening.
test('HOAACVLA - verify retail loan account', async ({ page }) => {
  console.log(`Verifying retail loan account: ${LOAN_ACCOUNT_NUMBER}`);

  // Select "core server" from the solution drop down
  console.log('Selecting Core Server...');
  await loanPage.selectCoreServer();

  // Step 2: Type menu option "HOAACVLA" in finacle
  console.log('Searching for HOAACVLA...');
  await loanPage.searchMenu('HOAACVLA');
  await page.waitForTimeout(3000);

  // Step 3: Function - V - Verify, Temporary a/c id - loan account number
  console.log('Selecting Verify function...');
  await loanPage.selectFunction('Verify');

  console.log('Entering temporary loan account ID to verify...');
  await loanPage.enterTemporaryAccountId(LOAN_ACCOUNT_NUMBER);

  // Click Go to load the loan account into the verification screen
  console.log('Clicking Go button...');
  await loanPage.clickGo();

  // Step 4: Visit General details
  console.log('Visiting General details tab...');
  await loanPage.visitLoanTab('General', 'generaldetails');

  // Step 5: Visit Loan details
  console.log('Visiting Loan details tab...');
  await loanPage.visitLoanTab('Loan Details', 'lasch');

  // Step 6: Visit A/c interest details
  console.log('Visiting A/c Interest tab...');
  await loanPage.visitLoanTab('A/C Interest', 'laacctinterest');

  // Step 7: Visit LA interest details
  console.log('Visiting LA Interest tab...');
  await loanPage.visitLoanTab('LA Interest', 'laint');

  // Step 8: Visit payment schedule details
  console.log('Visiting Payment Schedule tab...');
  await loanPage.visitLoanTab('Payment Schedule', 'lamnt');

  // Step 9: Visit related party details
  console.log('Visiting Related Party tab...');
  await loanPage.visitLoanTab('Related Party', 'relatedpartydetails');

  // Step 10: Visit MIS codes details
  console.log('Visiting MIS Codes tab...');
  await loanPage.visitLoanTab('MIS Codes', 'miscodes');

  // Step 11: Visit document details
  console.log('Visiting Document details tab...');
  await loanPage.visitLoanTab('Document', 'documentdetails');

  // Step 12: Visit account limits
  console.log('Visiting Account Limits tab...');
  await loanPage.visitLoanTab('Account Limits', 'acctlmt');

  // Step 13: Visit fees tab
  console.log('Visiting Fees tab...');
  await loanPage.visitLoanTab('Fees', 'lachrg');

  // Step 14: Click Submit - the loan account opening gets authorised/verified.
  // The confirmation screen shows "Verified A/c. ID: <number>" with an Accept
  // button to finalise the authorisation.
  console.log('Clicking Submit button...');
  await loanPage.submitForm();

  // If a Warning & Exception popup appears, click Accept to continue.
  await loanPage.acceptWarningPopup();

  const verifiedAccountNumber = await loanPage.getGeneratedLoanAccountNumber();
  console.log('=== VERIFIED LOAN ACCOUNT NUMBER:', verifiedAccountNumber, '===');

  console.log('Clicking Accept button...');
  await loanPage.clickAccept();

  // Logout
  console.log('Logging out...');
  await homePage.logout();
});
