import { test, expect } from '@playwright/test';
import { RetailLoanPayoffPage } from '../../pages/CoreBanking/RetailLoanPayoffPage';
import { loginToFinacle } from '../../helpers/finacleSetup';
import { CREDENTIALS } from '../../../data/credentials';
import { getSharedValue } from '../../helpers/sharedState';

// Maker user who creates the retail-loan payoff.
const USERNAME = CREDENTIALS.credentials.username;
const PASSWORD = CREDENTIALS.credentials.password;

// Loan account number generated by Retailloancreation.spec.ts.
const SHARED_LOAN_ACCOUNT = getSharedValue<string>('loanAccountId');
const LOAN_ACCOUNT_NUMBER = SHARED_LOAN_ACCOUNT ?? '3200000059';
if (SHARED_LOAN_ACCOUNT) console.log(`[SharedState] Using Loan Account ID from previous run: ${SHARED_LOAN_ACCOUNT}`);
const COLLECT_REFUND_ACCOUNT_ID = '7710003367';

test('HPAYOFF - payoff creation for retail loan', async ({ page }) => {
  test.setTimeout(300000);
  page.setDefaultTimeout(20000);

  const { homePage } = await loginToFinacle(page, USERNAME, PASSWORD);
  const payoffPage = new RetailLoanPayoffPage(page);

  try {
    const result = await payoffPage.createPayoff({
      loanAccountNumber: LOAN_ACCOUNT_NUMBER,
      transactionType: 'transfer customer induced',
      collectRefundAccountId: COLLECT_REFUND_ACCOUNT_ID,
      reasonCode: 'ASO',
    });

    console.log('====================================');
    console.log('Payoff creation transaction ID:', result.transactionId);
    console.log('Payoff creation message:', result.message);
    console.log('====================================');
  } finally {
    await homePage.logout().catch(() => {});
  }
});

// === STRICT ASSERTIONS INJECTION ===
test.afterEach(async ({ page }) => {
  const html = (await page.content()).toLowerCase();
  expect(html).not.toMatch(/core dump|internal server error/);
});
