import { test, expect } from '@playwright/test';
import { HomePage } from '../../pages/HomePages/HomePage';
import { SavingsBankAccountPage } from '../../pages/SavingsBankAccountPage';
import { loginToFinacle } from '../../helpers/finacleSetup';
import { CREDENTIALS } from '../../../data/credentials';

// Standing instruction verification (HSSIM, Function = V) MUST be performed by a
// DIFFERENT user than the maker who added the SI in standinginstructionsaddition.spec.ts.
const USERNAME = CREDENTIALS.secondCredentials.username;
const PASSWORD = CREDENTIALS.secondCredentials.password;

// Standing instruction serial number generated by standinginstructionsaddition.spec.ts.
// Update this with the latest generated SI number before running the verification.
const SI_SERIAL_NUMBER = 'NU1073';

let homePage: HomePage;
let siPage: SavingsBankAccountPage;

test.beforeEach(async ({ page }) => {
  test.setTimeout(300000);
  page.setDefaultTimeout(20000);

  // Step 1: Login to finacle with the verifying user (different from the maker).
  ({ homePage } = await loginToFinacle(page, USERNAME, PASSWORD));
  siPage = new SavingsBankAccountPage(page);
});

// HSSIM - Verify/authorise a standing instruction added by the maker.
test('HSSIM - verify standing instruction', async ({ page }) => {
  console.log(`Verifying standing instruction: ${SI_SERIAL_NUMBER}`);

  // Step 1: Select "core server" from the solution drop down.
  console.log('Selecting Core Server...');
  await siPage.selectCoreServer();

  // Step 2: Type menu option "HSSIM" in finacle.
  console.log('Searching for HSSIM...');
  await siPage.searchMenu('HSSIM');
  await page.waitForTimeout(3000);

  // Step 3: Function - V - Verify.
  console.log('Selecting Function (Verify)...');
  await siPage.selectSiDropdown('Verify');

  // Step 4: Standing instruction serial number - enter the generated SI number.
  console.log('Entering standing instruction serial number...');
  await siPage.setSiText(
    ['siSrlNo', 'srlNo', 'siSerialNo', 'serialNo', 'siSrlNum'],
    SI_SERIAL_NUMBER, 'SI serial number'
  );

  // Click Go to load the standing instruction into the verification screen.
  console.log('Clicking Go button...');
  await siPage.clickGo();
  await page.waitForTimeout(3000);

  // Step 5: Check the Header details.
  console.log('Visiting Header details tab...');
  await siPage.visitLoanTab('Header', 'header');
  await siPage.logVisibleFields('HSSIM Verify - Header details');

  // Step 6: Click on Instruction details and check.
  console.log('Visiting Instruction details tab...');
  await siPage.visitLoanTab('Instruction', 'instruction');
  await siPage.logVisibleFields('HSSIM Verify - Instruction details');

  // After reviewing the Instruction details, switch back to the Header details
  // tab before submitting.
  console.log('Switching back to Header details tab...');
  await siPage.visitLoanTab('Header', 'header');

  // Step 7: Click Submit - standing instruction is verified successfully.
  console.log('Clicking Submit button...');
  await siPage.submitForm();
  await siPage.acceptWarningPopup();
  await siPage.logScreenMessages();

  const statusMessage = await siPage.getStatusMessage();
  console.log('Exact status message:', statusMessage);
  expect(statusMessage).toBeTruthy();
  expect(statusMessage).toMatch(/(?:successfully|completed|verified|authorized|authorised|created|added|modified|deleted|disbursed|linked|generated)/i);
  console.log('SI verification status message:', statusMessage);
  expect(statusMessage).toBeTruthy();
  expect(statusMessage).toMatch(/(?:successfully|completed|verified|authorized|authorised|created|added|modified|deleted|disbursed|linked|generated)/i);

  // Step 8: Click Accept to return to the main page.
  console.log('Clicking Accept button...');
  await siPage.clickAccept();

  // Logout from the session.
  console.log('Logging out...');
  await homePage.logout();
});
