import { test, expect } from '@playwright/test';
import { getVerificationConfig } from '../../config/crmTestData';
import { login, setupDialogHandlers } from '../../config/crmSetup';
import { HomePage } from '../../pages/HomePages/HomePage';
import { AccountPage } from '../../pages/CoreBanking/AccountPage';
import { getSharedValue } from '../../helpers/sharedState';

// A/c Id generated by savingsaccountcreation.spec.ts. If a previous creation
// spec wrote the Account ID to shared state we use that; otherwise fall back
// to the hardcoded default.
const ACCOUNT_ID = getSharedValue((state) => state.accountId) ?? '7500001471';
console.log(`[Verification] Using Account ID: ${ACCOUNT_ID}`);

// Use the same verification user (finacletest01) as CIF approval to keep
// all verifications consistent under a single user.
const VERIFY_CONFIG = getVerificationConfig();

test.describe('Savings Account Verification', () => {
  test.use({ ignoreHTTPSErrors: true, actionTimeout: 30000 });

  let homePage: HomePage;
  let savingsAccountPage: AccountPage;

  test.beforeEach(async ({ page }) => {
    test.setTimeout(900000);
    ({ homePage } = await loginToFinacle(page, USERNAME, PASSWORD));
    savingsAccountPage = new AccountPage(page);
  });

  // HOAACVSB - Verify/authorise a savings account opening.
  test(`HOAACVSB - verify savings account creation - ${VERIFY_DATA.accountId}`, async () => {
    const result = await savingsAccountPage.verifySavingsAccountCreation(VERIFY_DATA);
    console.log('Exact verification result:', result);
    expect(result.success, `Expected verification success but got: ${result.message}`).toBe(true);
    expect(result.message).toBeTruthy();
    expect(result.message).toMatch(/(?:successfully|completed|verified|authorized|authorised|created|added|modified|deleted|disbursed|linked|generated|New A\/c\.?\s*ID|Account Number|Account No)/i);
    console.log('Verification status message:', result.message);

    // Logout
    console.log('Logging out...');
    await homePage.logout();
  });
});

// === STRICT ASSERTIONS INJECTION ===
test.afterEach(async ({ page }) => {
  const html = (await page.content()).toLowerCase();
  expect(html).not.toMatch(/core dump|internal server error/);
});
