import { test } from '@playwright/test';
import { HomePage } from '../../../pages/HomePage';
import { SavingsBankAccountPage } from '../../../pages/SavingsBankAccountPage';
import { loginToFinacle } from '../../helpers/finacleSetup';
import COMMON_DATA from '../../../data/common-data.json';

// Verification of a savings account opening (HOAACVSB) must be performed by a
// DIFFERENT user than the maker who created the account in
// savingsaccountcreation.spec.ts.
const USERNAME = COMMON_DATA.secondCredentials.username;
const PASSWORD = COMMON_DATA.secondCredentials.password;

// A/c Id generated by savingsaccountcreation.spec.ts. Update this with the
// latest created savings account number before running the verification.
const ACCOUNT_ID = '7500001471';

let homePage: HomePage;
let savingsAccountPage: SavingsBankAccountPage;

test.beforeEach(async ({ page }) => {
  test.setTimeout(300000);

  // Step 1: Login with the verifying user (different from the maker)
  ({ homePage } = await loginToFinacle(page, USERNAME, PASSWORD));
  savingsAccountPage = new SavingsBankAccountPage(page);
});

// HOAACVSB - Verify/authorise a savings account opening.
test('HOAACVSB - verify savings account creation', async ({ page }) => {
  console.log(`Verifying savings account creation: ${ACCOUNT_ID}`);

  // Select "core server" from the solution drop down
  console.log('Selecting Core Server...');
  await savingsAccountPage.selectCoreServer();
  await page.waitForTimeout(5000);

  // Step 2: Search for HOAACVSB (verification screen)
  console.log('Searching for HOAACVSB (verification screen)...');
  await savingsAccountPage.searchVerificationScreen('HOAACVSB');
  await page.waitForTimeout(3000);

  // Step 3: Function - V - Verify
  console.log('Selecting verify function option...');
  await savingsAccountPage.selectVerifyFunction();

  // Step 4: Temporary a/c id - the generated savings account number
  console.log('Entering temporary account ID...');
  await savingsAccountPage.enterTemporaryAccountId(ACCOUNT_ID);

  // Step 5: Click Go to load the account into the verification screen
  console.log('Clicking Go button...');
  await savingsAccountPage.acceptButton.click();
  await page.waitForTimeout(5000);

  // Step 6: Navigate through all tabs
  console.log('Navigating through all tabs...');
  await savingsAccountPage.navigateAllTabs();

  // Step 6b: Document tab is mandatory on the verification screen, else Submit
  // is blocked with "Document Details: Visit document information."
  console.log('Visiting Document details tab...');
  await savingsAccountPage.visitTabById('documentdetails');

  // Step 7: Click Submit - the account opening gets authorised/verified
  console.log('Clicking Submit button...');
  await savingsAccountPage.clickSubmit();

  // If a Warning & Exception popup appears, click Accept to continue.
  await savingsAccountPage.acceptWarningPopup();

  // Capture the actual Finacle status message after verification
  const statusMessage = await savingsAccountPage.getStatusMessage();
  console.log('Verification status message:', statusMessage);

  // Step 8: Logout
  console.log('Logging out...');
  await homePage.logout();
});
