import { test, expect } from '@playwright/test';
import { getVerificationConfig } from '../../config/crmTestData';
import { login, setupDialogHandlers } from '../../config/crmSetup';
import { HomePage } from '../../pages/HomePages/HomePage';
import { AccountPage } from '../../pages/CoreBanking/AccountPage';
import { getSharedValue } from '../../helpers/sharedState';

// A/c Id generated by savingsaccountcreation.spec.ts. If a previous creation
// spec wrote the Account ID to shared state we use that; otherwise fall back
// to the hardcoded default.
const ACCOUNT_ID = getSharedValue('accountId') ?? '7500001471';
console.log(`[Verification] Using Account ID: ${ACCOUNT_ID}`);

// Use the same verification user (finacletest01) as CIF approval to keep
// all verifications consistent under a single user.
const VERIFY_CONFIG = getVerificationConfig();

test.describe('Savings Account Verification', () => {
  test.use({ ignoreHTTPSErrors: true, actionTimeout: 30000 });

  let lastDialogMessages: string[] = [];
  let homePage: HomePage;
  let savingsAccountPage: AccountPage;

  test.beforeEach(async ({ page }) => {
    test.setTimeout(900000);
    setupDialogHandlers(page, lastDialogMessages);
    await login(page, VERIFY_CONFIG);

    homePage = new HomePage(page);
    savingsAccountPage = new AccountPage(page, lastDialogMessages);
  });

  // HOAACVSB - Verify/authorise a savings account opening.
  test('HOAACVSB - verify savings account creation', async ({ page }) => {
    console.log(`Verifying savings account creation: ${ACCOUNT_ID}`);

    // Select Core Server from the solution drop down
    console.log('Selecting Core Server...');
    await savingsAccountPage.selectCoreServer();
    await page.waitForTimeout(5000);

    // Search for HOAACVSB (verification screen)
    console.log('Searching for HOAACVSB (verification screen)...');
    await savingsAccountPage.searchVerificationScreen('HOAACVSB');
    await page.waitForTimeout(3000);

    // Function - V - Verify
    console.log('Selecting verify function option...');
    await savingsAccountPage.selectVerifyFunction();

    // Temporary a/c id - the generated savings account number
    console.log('Entering temporary account ID...');
    await savingsAccountPage.enterTemporaryAccountId(ACCOUNT_ID);

    // Click Go to load the account into the verification screen
    console.log('Clicking Go button...');
    await savingsAccountPage.acceptButton.click();
    await page.waitForTimeout(5000);

    // Navigate through all tabs
    console.log('Navigating through all tabs...');
    await savingsAccountPage.navigateAllTabs();

    // Document tab is mandatory on the verification screen, else Submit
    // is blocked with "Document Details: Visit document information."
    console.log('Visiting Document details tab...');
    await savingsAccountPage.visitTabById('documentdetails');

    // Click Submit - the account opening gets authorised/verified
    console.log('Clicking Submit button...');
    await savingsAccountPage.clickSubmit();

    // If a Warning & Exception popup appears, click Accept to continue.
    await savingsAccountPage.acceptWarningPopup();

    // Capture the actual Finacle status message after verification
    const statusMessage = await savingsAccountPage.getStatusMessage();
    console.log('Verification status message:', statusMessage);

    // Logout
    console.log('Logging out...');
    await homePage.logout();
  });
});

// === STRICT ASSERTIONS INJECTION ===
test.afterEach(async ({ page }) => {
  const html = (await page.content()).toLowerCase();
  expect(html).not.toMatch(/core dump|internal server error/);
});
