import { test } from '@playwright/test';
import { HomePage } from '../../pages/HomePages/HomePage';
import { AccountPage } from '../../pages/CoreBanking/AccountPage';
import { loginToFinacle } from '../../helpers/finacleSetup';
import COMMON_DATA from '../../../data/common-data.json';
import { CREDENTIALS } from '../../../data/credentials';

// Verification of a current account opening (HOAACVCA) must be performed by a
// DIFFERENT user than the maker who created the account in
// currentaccountcreation.spec.ts.
const USERNAME = CREDENTIALS.secondCredentials.username;
const PASSWORD = CREDENTIALS.secondCredentials.password;

// Current account verification (HOAACVCA) menu option.
const CURRENT_ACCOUNT_VERIFY_MENU = 'HOAACVCA';

// A/c Id generated by currentaccountcreation.spec.ts. Update this with the
// latest created current account number before running the verification.
const ACCOUNT_ID = '4600000112';


let homePage: HomePage;
let currentAccountPage: AccountPage;

test.beforeEach(async ({ page }) => {
  test.setTimeout(300000);

  // Step 1: Login with the verifying user (different from the maker)
  ({ homePage } = await loginToFinacle(page, USERNAME, PASSWORD));
  currentAccountPage = new AccountPage(page);
});

// HOAACVCA - Verify/authorise a current account opening.
test('HOAACVCA - verify current account creation', async ({ page }) => {
  console.log(`Verifying current account creation: ${ACCOUNT_ID}`);

  // Select "core server" from the solution drop down
  console.log('Selecting Core Server...');
  await currentAccountPage.selectCoreServer();
  await page.waitForTimeout(5000);

  // Step 2: Search the verification screen (HOAACVCA)
  console.log(`Searching for ${CURRENT_ACCOUNT_VERIFY_MENU} (verification screen)...`);
  await currentAccountPage.searchVerificationScreen(CURRENT_ACCOUNT_VERIFY_MENU);
  await page.waitForTimeout(3000);

  // Step 3: Function - V - Verify
  console.log('Selecting verify function option...');
  await currentAccountPage.selectVerifyFunction();

  // Step 4: Temporary a/c id - the generated current account number
  console.log('Entering temporary account ID...');
  await currentAccountPage.enterTemporaryAccountId(ACCOUNT_ID);

  // Step 5: Click Go to load the account into the verification screen
  console.log('Clicking Go button...');
  await currentAccountPage.acceptButton.click();
  await page.waitForTimeout(5000);

  // Step 6: Navigate through all tabs
  console.log('Navigating through all tabs...');
  await currentAccountPage.navigateAllTabs();

  // Step 6b: Document tab is mandatory on the verification screen, else Submit
  // is blocked with "Document Details: Visit document information."
  console.log('Visiting Document details tab...');
  await currentAccountPage.visitTabById('documentdetails');

  // Step 6c: Account Limits tab is also mandatory, else Submit is blocked with
  // "Account Limits: Visit account limits."
  console.log('Visiting Account Limits tab...');
  await currentAccountPage.visitAccountLimitsTab();

  // Step 7: Click Submit - the account opening gets authorised/verified
  console.log('Clicking Submit button...');
  await currentAccountPage.clickSubmit();

  // If a Warning & Exception popup appears, click Accept to continue.
  await currentAccountPage.acceptWarningPopup();

  // Capture the actual Finacle status message after verification
  const statusMessage = await currentAccountPage.getStatusMessage();
  console.log('Verification status message:', statusMessage);

  // Step 8: Logout
  console.log('Logging out...');
  await homePage.logout();
});
